name: 'Rust Setup'
description: 'Setup Rust environment with dependencies and caching'
inputs:
  install-deps:
    description: 'Install system dependencies'
    required: false
    default: 'true'
  setup-cache:
    description: 'Setup cargo cache'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libfontconfig1-dev libcfitsio-dev
    
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@1.88.0
      with:
        components: rustfmt, clippy
    
    - name: Cache Rust dependencies
      if: inputs.setup-cache == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        # Cache key includes OS, toolchain, and Cargo.lock
        key: ${{ runner.os }}-rust-cache
        # Cache the target directory and cargo registry
        cache-targets: true
        # Also cache the cargo index
        cache-all-crates: true